//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class KetQuaXoSo
    {
        public int KetQuaXoSoId { get; set; }
        public int LoaiVeSoId { get; set; }
        public System.DateTime NgayXoSo { get; set; }
        public int GiaiId { get; set; }
        public int SoTrung { get; set; }
    
        public virtual Giai Giai { get; set; }
        public virtual LoaiVeSo LoaiVeSo { get; set; }
    }
}
