//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EFModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhanPhoiVeSoEntities : DbContext
    {
        public PhanPhoiVeSoEntities()
            : base("name=PhanPhoiVeSoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DaiLy> DaiLies { get; set; }
        public virtual DbSet<Giai> Giais { get; set; }
        public virtual DbSet<KetQuaXoSo> KetQuaXoSoes { get; set; }
        public virtual DbSet<LoaiVeSo> LoaiVeSoes { get; set; }
        public virtual DbSet<PhieuDangKy> PhieuDangKies { get; set; }
        public virtual DbSet<PhieuPhatHanh> PhieuPhatHanhs { get; set; }
        public virtual DbSet<PhieuThu> PhieuThus { get; set; }
    }
}
