//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuPhatHanh
    {
        public int PhieuPhatHanhId { get; set; }
        public int DaiLyId { get; set; }
        public int LoaiVeSoId { get; set; }
        public System.DateTime NgayPhat { get; set; }
        public decimal SLPhat { get; set; }
        public Nullable<decimal> SLBanDuoc { get; set; }
    
        public virtual DaiLy DaiLy { get; set; }
        public virtual LoaiVeSo LoaiVeSo { get; set; }
    }
}
